name: Package Application with Pyinstaller

on:
    release:
      types: [ published ]
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

permissions: write-all

jobs:
  build:

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pyinstaller
            pip install -r requirements.txt

      - name: Build
        run: pyinstaller -F weblogin.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: weblogin
          path: dist/weblogin.exe

      - name: Upload to release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} dist/weblogin.exe