name: Package Application with Nuitka

on:
    release:
      types: [ published ]
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

permissions: write-all

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019, ubuntu-latest, macos-latest]
        arch: [x64]
        include:
          - os: macos-latest
            arch: arm64
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: weblogin.py
          onefile: true

      - name: Rename Executable
        if: matrix.os != 'windows-2019'
        run: |
          mv build/weblogin.bin build/weblogin-${{ runner.os }}-${{ matrix.arch }}

      - name: Upload artifact (Windows)
        if: matrix.os == 'windows-2019'
        uses: actions/upload-artifact@v2
        with:
          name: weblogin-${{ runner.os }}-${{ matrix.arch }}
          path: build/weblogin.exe

      - name: Upload artifact (non-Windows)
        if: matrix.os != 'windows-2019'
        uses: actions/upload-artifact@v2
        with:
          name: weblogin-${{ runner.os }}-${{ matrix.arch }}
          path: build/weblogin-${{ runner.os }}-${{ matrix.arch }}

      - name: Upload to release (Windows)
        if: github.event_name == 'release' && matrix.os == 'windows-2019'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} build/weblogin.exe
      - name: Upload to release (non-Windows)
        if: github.event_name == 'release' && matrix.os != 'windows-2019'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} build/weblogin-${{ runner.os }}-${{ matrix.arch }}